<br /><br /><center>View script for controller <b>Bug</b> and script/action name <b>index</b></center>

<a href="<?php echo $this->url(
        array('controller'=>'bug','action'=>'submit'));
?>">Submit a bug</a>
<br />
<a href="<?php echo $this->url(
        array('controller'=>'bug','action'=>'list'));
?>">Show bugs</a>

<br />

<a href="<?php echo $this->url(
        array('controller'=>'bug','action'=>'list2'));
?>">Show bugs with paginator</a>