<tr>
    <td><a href='<?php echo $this->baseUrl();?>/bug/edit/id/<?php echo $this->id; ?>'>Edit</a> |
        <a href='<?php echo $this->baseUrl();?>/bug/delete/id/<?php echo $this->id; ?>'>Delete</a></td>
    <td><?php echo date('m/d/y', $this->date); ?></td>
    <td><?php echo $this->priority; ?></td>
    <td><?php echo $this->status; ?></td>
    <td><?php echo $this->url; ?></td>
    <td><?php echo $this->author; ?></td>
    <td><?php echo $this->description; ?></td>
</tr>
