<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php $this->headTitle(); ?>


        <?php echo $this->headScript(); ?>

        <?php
        //echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/layout.css');
        echo $this->loadSkin($this->skin);
        ?>

    </head>


    <body>
        <div id="pageWrapper">
            <div id="header">
                <h1><a href="<?php echo $this->baseUrl() ?>">
                        Zend Framework CMS</a></h1>
            </div>
            <div id="nav">

                <a href="<?php
        echo $this->url(
                array('controller' => 'bug', 'action' => 'index'));
        ?>">Bugs</a>

                <a href="<?php
        echo $this->url(
                array('controller' => 'page', 'action' => 'list'));
        ?>">List page</a>


                 <?php echo "asdfs". $this->navigation()->breadcrumbs(); ?>

<?php echo $this->layout()->nav; ?>&nbsp;
            </div>
            <div id="sidebar">
                <div id="subNav">
<?php echo $this->layout()->subNav; ?>&nbsp;
                </div>
                <div id="adminMenu">
<?php echo $this->layout()->adminMenu; ?>&nbsp;
                </div>
                <div id="userForm">
<?php echo $this->layout()->userForm; ?>&nbsp;
                </div>
            </div>
            <div id="main">
<?php echo $this->layout()->content ?>&nbsp;
            </div>
            <div id="footer">
                <p><em>
                        Powered by the Zend Framework
                    </em>
                </p>
            </div>
        </div>
    </body>


</html>
