<tr>
    <td class='links'>
        <a href='<?php echo $this->baseUrl(); ?>/menu/edit/id/<?php echo $this->id; ?>'>Edit</a> |
        <a href='<?php echo $this->baseUrl(); ?>/menuitem/index/menu/<?php echo $this->id; ?>'>
            Manage Menu Items</a> |
        <a href='<?php echo $this->baseUrl(); ?>/menu/delete/id/<?php echo $this->id; ?>'>Delete</a>
    </td>
    <td><?php echo $this->name ?></td>
</tr>
